### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by samedovzaur** [qdrant/qdrant-web-ui#126]
I'm keep getting this error do you guys know why?

**Comment by uguraydrd** [comment]
Is there any update?

**Comment by timvisee** [comment]
What request are you trying to execute through the web UI?

Are you sure the HTTP method you're using is correct?

**Comment by uguraydrd** [comment]
Actually, I would like to run the visualization from this url with sshpass on UI:

http://localhost:6333/dashboard/

I am getting the same error with @samedovzaur:

Visualization Unsuccessful, error: {"message":"Request failed with status code 405","name":"AxiosError","stack":"AxiosError: Request failed with status code 405\n at qte (http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:959)\n at XMLHttpRequest.d (http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:4075)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"baseURL":"http://localhost:6333/dashboard/","method":"post","url":"collections/online_retail/points/scroll","data":"{\"limit\":500,\"with_vector\":true}"},"code":"ERR_BAD_REQUEST","status":405}

**Comment by dietmar** [comment]
We also have this problem. We are running a dockerized qdrant and access it via nginx with TLS. We tried to debug the proxying and everything, but couldn't get it to work.
Accessing the web UI in general works. But clicking on "RUN"  in visualize causes the same error as above.
A curl POST call directly on the host also causes a 405, so it looks like it's not an nginx or TLS problem.
```
curl -v --data '' http://localhost:6333/dashboard/collections/<mycollection>/points/scroll

*   Trying 127.0.0.1:6333...
* Connected to localhost (127.0.0.1) port 6333 (#0)
> POST /dashboard/collections/<mycoellection>/points/scroll HTTP/1.1
> Host: localhost:6333
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< content-length: 50
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< content-type: text/plain; charset=utf-8
< date: Fri, 09 Feb 2024 15:36:27 GMT
< 
* Connection #0 to host localhost left intact
Request did not meet this resource's requirements.
```

Any info we can provide to help narrow this down?

**Comment by PylotLight** [comment]
Got this issue as well, any known workarounds or fixes?

**Comment by pahlers** [comment]
> Actually, I would like to run the visualization from this url with sshpass on UI:
> 
> http://localhost:6333/dashboard/
> 
> I am getting the same error with [@samedovzaur](https://github.com/samedovzaur):
> 
> Visualization Unsuccessful, error: {"message":"Request failed with status code 405","name":"AxiosError","stack":"AxiosError: Request failed with status code 405\n at qte ([http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:959)\n](http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:959)%5Cn) at XMLHttpRequest.d ([http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:4075)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json](http://localhost:6333/dashboard/assets/index-22a6d29c.js:295:4075)%22,%22config%22:%7B%22transitional%22:%7B%22silentJSONParsing%22:true,%22forcedJSONParsing%22:true,%22clarifyTimeoutError%22:false%7D,%22adapter%22:%5B%22xhr%22,%22http%22%5D,%22transformRequest%22:%5Bnull%5D,%22transformResponse%22:%5Bnull%5D,%22timeout%22:0,%22xsrfCookieName%22:%22XSRF-TOKEN%22,%22xsrfHeaderName%22:%22X-XSRF-TOKEN%22,%22maxContentLength%22:-1,%22maxBodyLength%22:-1,%22env%22:%7B%7D,%22headers%22:%7B%22Accept%22:%22application/json), text/plain, _/_","Content-Type":"application/json"},"baseURL":"[http://localhost:6333/dashboard/","method":"post","url":"collections/online_retail/points/scroll","data":"{\"limit\":500,\"with_vector\":true}"},"code":"ERR_BAD_REQUEST","status":405}](http://localhost:6333/dashboard/%22,%22method%22:%22post%22,%22url%22:%22collections/online_retail/points/scroll%22,%22data%22:%22%7B%5C%22limit%5C%22:500,%5C%22with_vector%5C%22:true%7D%22%7D,%22code%22:%22ERR_BAD_REQUEST%22,%22status%22:405%7D)

Remove the trailing slash. Use http://localhost:6333/dashboard.

Its the usage of a regular expression to alter a url which is broken.

https://github.com/qdrant/qdrant-web-ui/blob/04115acafc04b155df77af0b25bdfaea6baa32f0/src/common/utils.js#L3
```js
export const getBaseURL = function () {
  const url = new URL(window.location.href);
  const pathname = url.pathname.replace(/dashboard$/, '');
  return new URL(pathname, url.href).href;
};
```

The following code will fix this issue
```js
export const getBaseURL = function () {
  const url = new URL(window.location.href);
  const pathname = url.pathname.replace(/dashboard\/?$/, '');
  return new URL(pathname, url.href).href;
};
```
